### ISSUE TITLE
Socket IO not syncing "thing" in default app

### ISSUE THREAD

**Issue by EliKrumholz** [angular-fullstack/generator-angular-fullstack#2491] opened 2017-02-05 00:14 UTC
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.2
Node | 6.9.5
npm | 3.9.5
Operating System | OS X 10 and Heroku

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y
SocketIO | Y

"Things" in the main view are not syncing automatically when created or deleted, a full page refresh is required to see the updates. I observed this behavior on both OSX 10.12 and on heroku using default settings for the generator at v4.1.2. Just a default build of the generator deployed to heroku should replicate this bug as far as I can tell.

I am not seeing any errors on either the client side or the server side, any suggestions on where to start tracking down this bug?

**Comment by Ernisto** [comment] 2017-02-05 14:37
# Problem
I have researched this issue and found reason why this doesn't work.

In **thing.events.js** file
_`./server/api/thing/thing.events.js`_

  ```javascript
// Register the event emitter to the model events
for(var e in events) {
    let event = events[e];
    Thing.schema.post(e, emitEvent(event));
}
```

As you can see inside `for` loop **remove** and **save** events are applied to `Thing` Schema thorough **POST HOOKS** . And this hooks never called. I think this happens because we are applying HOOKS to Shema after Thing model is already created in model file:
```javascript
export default mongoose.model('Thing', ThingSchema);
```

# Solution

Problem solved when I applied hooks before model created:
  In **thing.model.js** file
_`./server/api/thing/thing.model.js`_

  ```javascript
'use strict';

import mongoose from 'mongoose';

var ThingSchema = new mongoose.Schema({
    name: String,
    info: String,
    active: Boolean
});

require('./thing.events').applyHooks(ThingSchema);

export default mongoose.model('Thing', ThingSchema);
```


And **thing.events.js** was modified to export `applyHook` function which will apply schema hooks before mongoose model is created.
_`./server/api/thing/thing.events.js`_

```javascript
/**
 * Thing model events
 */

'use strict';

import {EventEmitter} from 'events';
var ThingEvents = new EventEmitter();

// Set max event listeners (0 == unlimited)
ThingEvents.setMaxListeners(0);

// Model events
var events = {
  save: 'save',
  remove: 'remove'
};

function emitEvent(event) {
  return function(doc) {
    ThingEvents.emit(`${event}:${doc._id}`, doc);
    ThingEvents.emit(event, doc);
  };
}

export function applyHooks(schema) {
// Register the event emitter to the model events
  for(var e in events) {
    let event = events[e];
    schema.post(e, emitEvent(event));
  }
}

export default ThingEvents;

```

**Comment by Ernisto** [comment] 2017-02-05 14:44
I might be wrong in reasons but this solution works.

**Comment by EliKrumholz** [comment] 2017-02-05 20:21
Nice work, Ernisto, thanks! I was able to replicate your solution and it fixes the issue on my heroku deployment.

I think you're correct about `Thing.schema.post` not working properly in `./server/api/thing/thing.events.js` but I actually think this is on the end of Mongoose, rolling back the version to `"mongoose": "~4.7.9"` in `package.json` seems to fix this error too, which also means it's probably related to #2479, so rolling back mongoose for now and opening an issue with mongoose is probably the best solution.

**Comment by Ernisto** [comment] 2017-02-07 08:23
Thank you!

I haven't tried older versions. I thought something was broken in `angular-fullstack` after refactor maybe or something else.

**Comment by Awk34** [comment] 2017-02-07 16:25
Closing as duplicate of #2479

**Closed by Awk34** 2017-02-07 16:25 UTC
