### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by speedingdeer** [angular-fullstack/generator-angular-fullstack#1507] opened 2015-12-18 23:12 UTC
I've installed the latest. I get the warning when I run the server and I can't figure it out. The log updates with each request. It's a pure generated code, I haven't added anything yet myself.

Warning: a promise was created in a handler but was not returned from it
    at executeSql (/Users/speedingdeer/code/lucy/master/node_modules/sequelize/lib/dialects/sqlite/query.js:96:19)
From previous event:
    at Promise.then (/Users/speedingdeer/code/lucy/master/node_modules/sequelize/lib/promise.js:21:17)
    at Database.<anonymous> (/Users/speedingdeer/code/lucy/master/node_modules/sequelize/lib/dialects/sqlite/query.js:258:14)
    at /Users/speedingdeer/code/lucy/master/node_modules/sequelize/lib/dialects/sqlite/query.js:91:19
From previous event:
    at [object Object].Query.run (/Users/speedingdeer/code/lucy/master/node_modules/sequelize/lib/dialects/sqlite/query.js:89:13)
    at /Users/speedingdeer/code/lucy/master/node_modules/sequelize/lib/sequelize.js:798:18
From previous event:
    at Promise.then (/Users/speedingdeer/code/lucy/master/node_modules/sequelize/lib/promise.js:21:17)
    at [object Object].Model.findAll (/Users/speedingdeer/code/lucy/master/node_modules/sequelize/lib/model.js:1369:6)
    at [object Object].Model.findOne (/Users/speedingdeer/code/lucy/master/node_modules/sequelize/lib/model.js:1490:34)
    at E4Store.get (/Users/speedingdeer/code/lucy/master/node_modules/express-sequelize-session/lib/e4store.js:51:29)
    at session (/Users/speedingdeer/code/lucy/master/node_modules/express-session/index.js:408:11)
    at Layer.handle [as handle_request] (/Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/index.js:312:13)
    at /Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/index.js:271:10)
    at initialize (/Users/speedingdeer/code/lucy/master/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/index.js:312:13)
    at /Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/Users/speedingdeer/code/lucy/master/node_modules/cookie-parser/index.js:68:5)
    at Layer.handle [as handle_request] (/Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/speedingdeer/code/lucy/master/node_modules/express/lib/router/index.js:312:13)

**Comment by speedingdeer** [comment] 2015-12-19 13:03
I'm on OSX, Node 5.0

**Comment by dicer2000** [comment] 2015-12-21 03:44
I'm having same issue on OS X, Node 5 & sqlite.  It doesn't seem to happen with Mongo

**Comment by speedingdeer** [comment] 2015-12-21 08:58
Well, it says it's an warning in sql, it can't happen with Mongo :)

**Comment by Awk34** [comment] 2015-12-21 17:33
It's just a warning that Bluebird spits out, caused by Sequelize. Take a look at [this sequelize PR](https://github.com/sequelize/sequelize/pull/4862). I believe the warning will be fixed if you update to the latest sequelize version.

**Closed by Awk34** 2015-12-21 17:33 UTC
Labels: investigate

**Comment by speedingdeer** [comment] 2015-12-21 17:50
Thanks I will try to update Sequelize. BTW Bluebird is taken somewhere as dependency in v2. The current version is 3 it might cause this issue too. https://github.com/petkaantonov/bluebird/issues/846 They've described the issue with similar warning which was fixed in version 3. Not sure if it's related.

**Comment by Awk34** [comment] 2015-12-21 17:56
Sequelize master uses [Bluebird ^3.0.5](https://github.com/sequelize/sequelize/blob/master/package.json#L35)

**Comment by miguelalche** [comment] 2015-12-25 19:35
I'm also having this problem, could you solve it @speedingdeer ?

**Comment by speedingdeer** [comment] 2015-12-30 23:53
@miguelalche, No I haven't solved it. It still the same and I've installed the latest sequelize, trying different dialects, fixing controller code by hand etc.

**Comment by speedingdeer** [comment] 2015-12-30 23:56
@miguelalche I took a look at the commit attached to your question and downgrade works for me. Sequelize v3.13 seemed to works fine.

**Comment by jeffbuhrt** [comment] 2016-01-27 22:01
This is addressed (fixed) in the pull request for #1477 along with other sequelize issues for the generated demo.

**Comment by chovy** [comment] 2016-07-12 20:07
I'm still getting this.

**Comment by josephbisaillon** [comment] 2016-07-30 03:36
Also getting this with a fresh pull
