### ISSUE TITLE
Authentication Problems

### ISSUE THREAD

**Issue by tomhalley** [angular-fullstack/generator-angular-fullstack#1521] opened 2015-12-29 14:31 UTC
Two problems with the framework authentication I've encountered so far:

1. Logging in with Facebook AND Google+ is not possible. Obviously the server code is expecting you to log in with one or the other, but if you log in with a second social media accounnt with the same email as the first, instead of just appending the secondary provider data to the initial user account, it actually tries to create a new user account without first checking, which of course fails becuase of the email being unique.

2. Page refresh on Logging in with Google or Facebook. Is that really necessary? I thought the whole purpose of a single page application was to avoid this, as logging in currently destroys all client state.

**Comment by Awk34** [comment] 2015-12-29 20:19
I believe 1 is a dupe of #359 .

**Closed** 2016-05-11 19:43 UTC
