### ISSUE TITLE
gulp build and gulp serve:dist  generates GET 404 errors.

### ISSUE THREAD

**Issue by hcbelias** [angular-fullstack/generator-angular-fullstack#1928] opened 2016-05-25 04:36 UTC
When running gulp build or gulp serve:dist and accessing the project through localhost:9000 or the project in production the browser console and command prompt spits out 404 not found.

Item | Answer
----- | -----
generator-angular-fullstack | 3.6.1
Node | v6.0.0
npm | 3.8.6
Operating System | Windows 8

Item | Answer
----- | -----
Transpiler | Babel 
Markup | Jade
CSS | SCSS 
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine 
DB | MongoDB 
Auth | N

You can check the example here:

https://github.com/hcbelias/casamento/tree/issue_example

**Comment by Awk34** [comment] 2016-05-25 13:39
I believe this is a duplicate of #370

**Comment by hcbelias** [comment] 2016-05-25 16:49
Yup.... thanks for helping....

For those who may interest, in my case, to fix this issue I changes my .git/config file....

[core]
        /* other attrs */
	eol = lf     => Added
	autocrlf = input   => Added

**Comment by hcbelias** [comment] 2016-06-07 01:12
This would impact only HTML/JADE files?

**Closed** 2016-06-07 01:34 UTC
Labels: duplicate
