### ISSUE TITLE
Unable to run the gulp server installed through fullstack

### ISSUE THREAD

**Issue by prashanth-sams** [angular-fullstack/generator-angular-fullstack#2043] opened 2016-07-06 11:47 UTC
```
Prashanths-MacBook-Pro-2:PickOH prashanthsams$ gulp start:server
[17:07:57] Requiring external module babel-register
[17:08:02] Using gulpfile ~/Documents/PickOH/gulpfile.babel.js
[17:08:02] Starting 'start:server'...
[17:08:02] Finished 'start:server' after 15 ms
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/prashanthsams/Documents/PickOH/server/**/*
[nodemon] starting `node server`
/Users/prashanthsams/Documents/PickOH/server/config/seed.js:17
Thing.sync().then(function () {
     ^

TypeError: Cannot read property 'sync' of undefined
    at Object.<anonymous> (seed.js:11:1)
    at Module._compile (module.js:435:26)
    at loader (/Users/prashanthsams/Documents/PickOH/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/prashanthsams/Documents/PickOH/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (app.js:13:22)
    at Module._compile (module.js:435:26)
    at loader (/Users/prashanthsams/Documents/PickOH/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/prashanthsams/Documents/PickOH/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/prashanthsams/Documents/PickOH/server/index.js:12:28)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
[nodemon] app crashed - waiting for file changes before starting...
```

![asdf](https://66.media.tumblr.com/2a890e1b189ea0a186fe2e21a6b5b8be/tumblr_o9w69cd5lL1vze00qo1_1280.png)

**Comment by Koslun** [comment] 2016-07-06 12:25
Well I don't think you're actually supposed to run "gulp start:server" for any use case really.

`gulp serve` starts the server in development use, think you're looking for that.

If there is an actual issue it is imperative that you actually fill in what version and configuration you're using. There are many issues fixed between versions and a very start difference between the different major versions.

So edit this with your version and configuration.

```
Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc
```

**Comment by prashanth-sams** [comment] 2016-07-06 19:28
@Koslun still facing similar issue :(

Prashanths-MacBook-Pro-2:PickOH prashanthsams$ gulp serve
[00:55:20] Requiring external module babel-register
[00:55:25] Using gulpfile ~/Documents/PickOH/gulpfile.babel.js
[00:55:25] Starting 'serve'...
[00:55:25] Starting 'clean:tmp'...
[00:55:25] Starting 'constant'...
[00:55:25] Starting 'env:all'...
[00:55:25] Finished 'env:all' after 63 ms
[00:55:25] Finished 'clean:tmp' after 278 ms
[00:55:25] Finished 'constant' after 283 ms
[00:55:25] Starting 'lint:scripts'...
[00:55:25] Starting 'lint:scripts:client'...
[00:55:25] Starting 'lint:scripts:server'...
[00:55:25] Starting 'inject'...
[00:55:25] Starting 'inject:js'...
[00:55:26] Starting 'inject:css'...
[00:55:26] Starting 'inject:scss'...
[00:55:26] gulp-inject Nothing to inject into index.html.
[00:55:26] gulp-inject 5 files into app.scss.
[00:55:26] Finished 'inject:css' after 302 ms
[00:55:26] Finished 'inject:scss' after 306 ms
[00:55:26] gulp-inject 25 files into index.html.
[00:55:26] Finished 'inject:js' after 554 ms
[00:55:26] Finished 'inject' after 556 ms
[00:55:26] Finished 'lint:scripts:client' after 946 ms
[00:55:26] Finished 'lint:scripts:server' after 938 ms
[00:55:26] Finished 'lint:scripts' after 995 ms
[00:55:26] Starting 'wiredep:client'...
[00:55:27] Finished 'wiredep:client' after 95 ms
[00:55:27] Starting 'transpile:client'...
[00:55:27] Starting 'styles'...
[00:55:27] Finished 'styles' after 970 ms
[00:55:28] Finished 'transpile:client' after 1.26 s
[00:55:28] Starting 'start:server'...
[00:55:28] Finished 'start:server' after 7.72 ms
[00:55:28] Starting 'start:client'...
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/prashanthsams/Documents/PickOH/server/**/*
[nodemon] starting `node server`
/Users/prashanthsams/Documents/PickOH/server/config/seed.js:17
Thing.sync().then(function () {
     ^

TypeError: Cannot read property 'sync' of undefined
    at Object.<anonymous> (seed.js:11:1)
    at Module._compile (module.js:435:26)
    at loader (/Users/prashanthsams/Documents/PickOH/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/prashanthsams/Documents/PickOH/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (app.js:13:22)
    at Module._compile (module.js:435:26)
    at loader (/Users/prashanthsams/Documents/PickOH/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/prashanthsams/Documents/PickOH/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/prashanthsams/Documents/PickOH/server/index.js:12:28)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by prashanth-sams** [comment] 2016-07-06 20:31
Prashanths-MacBook-Pro-2:PickOHLegacy prashanthsams$ yo angular-fullstack PickOH

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Out of the box I create an AngularJS app with an Express server.

# Client

? What would you like to write scripts with? Babel
? What would you like to write markup with? (Use arrow keys)
? What would you like to write markup with? HTML
? What would you like to write stylesheets with? (Use arrow keys)
  CSS 
? What would you like to write stylesheets with? Sass
? What Angular router would you like to use? (Use arrow keys)
  ngRoute 
? What would you like to write scripts with? Babel
? What Angular router would you like to use? uiRouter
? Would you like to include Bootstrap? Yes
? What would you like to write scripts with? Babel
? What would you like to write markup with? HTML
? What would you like to write stylesheets with? Sass
? What Angular router would you like to use? uiRouter
? Would you like to include UI Bootstrap? Yes
? What would you like to write scripts with? Babel
? What would you like to write markup with? HTML
? What would you like to write stylesheets with? Sass
? What Angular router would you like to use? uiRouter

# Server

? What would you like to use for data modeling? Sequelize (MySQL, SQLite, MariaDB, PostgreSQL)
? Would you scaffold out an authentication boilerplate? Yes
? Would you like to include additional oAuth strategies? Google, Facebook, Twitter
? Would you like to use socket.io? Yes

# Project

? Would you like to use Gulp or Grunt? Gulp
? What would you like to write tests with? 
? What would you like to write tests with? Jasmine
You're using the fantastic NgComponent generator.

Initializing yo-rc.json configuration.
...

**Comment by Awk34** [comment] 2016-07-06 20:36
Looking at your stack trace, [Thing](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.7.5/templates/app/server/config/seed(models).js#L7) is undefined. Ensure that the endpoint files exist. You might have exited the generator before the endpoint could be created. Try re-generating.

**Comment by prashanth-sams** [comment] 2016-07-06 20:57
@Awk34 I tried re-generating it, but I'm unable to proceed in a point as shown in the below image, (I faced the same last time when I run yo ending with the following [issue](http://stackoverflow.com/questions/38222486/js-library-installation-quits-in-the-middle-through-mac-terminal)
![as](http://i.imgur.com/NKgGyGd.png)

**Comment by Awk34** [comment] 2016-07-06 20:59
@prashanth-sams I don't see anything wrong in that image

**Comment by prashanth-sams** [comment] 2016-07-06 21:02
@Awk34 Does it work if I quit (ctrl+c) the process in terminal; as I've been waiting for the generator to complete for than 45 mins :(  and does quitting at this point affect running gulp server?

**Comment by Awk34** [comment] 2016-07-06 21:04
@prashanth-sams it does. Try running instead with `yo angular-fullstack --skip-install` this will skip the `npm install && bower install` step. You can then try to sort out dependency installation after the generator completes.

**Comment by Koslun** [comment] 2016-07-06 21:05
@prashanth-sams What version are you using? Can see the config above but can't see the version number.

**Comment by prashanth-sams** [comment] 2016-07-06 21:15
├─┬ generator-angular-fullstack@3.7.6
│ ├─┬ babel-plugin-syntax-class-properties@6.8.0
│ │ └─┬ babel-runtime@6.9.2
│ │   ├── core-js@2.4.0
│ │   └── regenerator-runtime@0.9.5

├─┬ npm@2.14.7

node v4.2.3

OS X El Capitan, 10.11.4

**Comment by prashanth-sams** [comment] 2016-07-06 21:23
@Awk34 @Koslun any changes required in these config settings?

**Comment by Awk34** [comment] 2016-07-06 21:37
At this point I'm pretty confident that the problem is not with the generator, so I'm closing this issue. It looks like the generator runs fine, but you're having issues installing your dependencies (probably network issues).

**Closed by Awk34** 2016-07-06 21:37 UTC
Labels: need details

**Comment by prashanth-sams** [comment] 2016-07-06 21:40
@Awk34 Thank you for the valuable comments; it worked finally after installing libraries separately through ```npm install && bower install```

**Comment by Awk34** [comment] 2016-07-06 22:27
@prashanth-sams good to hear
